### ISSUE TITLE
PHPageBuilder page not found 

### ISSUE THREAD

**Issue by zunaidmiah** [HansSchouten/Laravel-Pagebuilder#121]
I follow your instruction but i got this issue
![image](https://user-images.githubusercontent.com/45538749/163547030-78781f5d-5de5-4089-87a9-9c57003c471f.png)

**Comment by HansSchouten** [comment]
This base URL (everything up to /admin) is probably not stored in the config file

**Comment by zunaidmiah** [comment]
Okay. So what can i do now?

**Comment by HansSchouten** [comment]
I think check/debug the URLs in your .env or pagebuilder config file. I always use clean URLs without sub folders as base URL for websites, so probably the URL is the source of the issue.

**Comment by zunaidmiah** [comment]
Okay. Please let me one thing, how i will update config/pagebuilder.php file?
I mean what i need to be changed or updated of this file.

**Comment by HansSchouten** [comment]
Run the second command in the Installation steps to publish the config file: https://github.com/HansSchouten/Laravel-Pagebuilder#installation

**Comment by zunaidmiah** [comment]
when run all command for installation then i got config file. But from index page when i click get started link then show that error message which i add in screenshot . I can't ran this project. Help me please

**Comment by zunaidmiah** [comment]
Will you please provide a video step by step how will integrate your pagebuilder with fresh laravel project.
It;s really help me if you'll provide me this.
Thanks for your consideration and time

**Comment by HansSchouten** [comment]
Unfortunately at the moment I don't have time to create that or check out on all tickets. But what I can say is that it is most likely due to the URL you are using (I directly work directly on (sub)domains on the many VPSes I own, so never locally) hence my URLs are always https://www.example.com. So there could be an issue around that. Probably if you host the project directly in http://localhost it would work fine. And to find the root cause search through the project to the code where it outputs "check your URL" there would be something going wrong if you debug `dd()` the state of the variables/methods around there.

**Comment by Gagandeep188** [comment]
hey zunaidmiah have you got the error????
