### ISSUE TITLE
ErrorException Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by alifu** [HansSchouten/Laravel-Pagebuilder#2]
I get error "ErrorException Trying to access array offset on value of type null" in login website manager. 

<img width="427" alt="Screen Shot 2020-01-20 at 17 10 48" src="https://user-images.githubusercontent.com/15167849/72713398-f1c4b880-3ba7-11ea-8c56-a76bd4054ee7.png">

**Comment by HansSchouten** [comment]
Hi Alif, the config is not up-to-date with PHPageBuilder v0.5.0. I am working on a fix now.

**Comment by HansSchouten** [comment]
Can you post the line number at which the error occurs? I see the config is already up-to-date.

**Comment by alifu** [comment]
maybe you can update tag. because if i use tag v0.1.0, in composer.json is not update yet. and for migration maybe get some update too, because you update sql in phpagebuilder. 

this lib is very good. thank you for build this, 😁.

**Comment by HansSchouten** [comment]
Thanks for your sugegstions, I just created a new release in Laravel-Pagebuilder. I fully agree with adding migrations instead of depending on the sql of the main repo, I will add these in the near future. PHPageBuilder is still in active development without a first full release, so it is still a bit shaky, but I appreciate all early feedback!
Did you manage to fix the error you showed above? Or can you maybe provide a clear stack trace of what happened.

**Comment by alifu** [comment]
i just comment line 59 in Core/helper.php, because value of `$phpb_flash[$key]` is null. i don't know why is work.

**Comment by HansSchouten** [comment]
For me line 59 is a line of comments, so I think it is because you are still running the older code. I know this issue and have fixed it earlier.

**Comment by alifu** [comment]
thank you so much, it’s working now. 😁
