### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by virgiltu** [HansSchouten/Laravel-Pagebuilder#29]
I know very short title. 

So I installed it on a clean Laravel 7 system.  admin is blank cant get a login screen 
Than I thought maybe Laravel 5.8 will work so I did a clean install on this. However i am still getting a blank screen. The only thing that loads is the favicon. 

No error just Page Not Found

Any ideas?

**Comment by HansSchouten** [comment]
Are you sure your config is correct? Can you check the other already closed issues, this has happened before.

**Comment by virgiltu** [comment]
> Are you sure your config is correct? Can you check the other already closed issues, this has happened before.

Yhes the APP_URL=http://127.0.0.1:8000 is what the issue was. 

I am working to bring this to Tailwind, i feed like that is what this builder needs.

**Comment by HansSchouten** [comment]
Thank you for the suggestion. I am planning to build a full demo theme with blocks based on Bootstrap, but Tailwind is also a good idea.

1. Your project should have one theme that is active at any time, so after you've created a theme you configure it in your `phpagebuilder.php` config file.
1. To set an image or a category you can create a `config.php` file in the folder of a block and create an array with `"category" => "Your name here"`. In order to add images, have a look to this example: https://github.com/HansSchouten/PHPageBuilder-Laravel-Screenshots. I am planning to integrate it in the Laravel package.
1. This project is using GrapesJS, but with some custom javascript for creating blocks with pure html and to allow for dynamic blocks with server-rendered content. Therefore it is not always possible to simply enable a feature of GrapesJS. However, a html code editor is high on my wish list, so it will be coming soon.
