### ISSUE TITLE
Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()

### ISSUE THREAD

**Issue by akbarabustang** [HansSchouten/Laravel-Pagebuilder#53]
Got this error when using Laravel 8
error location  http://localhost:8000/admin
Any idea about this issue ?

**Comment by HansSchouten** [comment]
That means you don't have a `pagebuilder.php` file in your `config` folder. This is because `php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config` has not been runned, or you could not run this because of the recent issues.
However, I just released a new version, so please upgrade.

**Comment by elbouziani** [comment]
good night , i have the same issue when i try to click save button  ( the response of xhr request is Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()  )

**Comment by HansSchouten** [comment]
This warning means you are calling the `handleRequest()` while you are having login or the default website manager disabled [see here](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/PHPageBuilder.php#L258). In that case you should not call this method, but manually call the two methods it suggests. Probably you are calling the `handleRequest()` method somewhere yourself? Or if you don't know how it is called, please add `debug_print_backtrace();` to the `handleRequest()` method and look what is happening.
